services:
  # Frontend service (static site) - DEMO ONLY
  - type: web
    name: app-email-attendant
    env: static
    buildCommand: "cd appclient && npm install --legacy-peer-deps && npm run build"
    staticPublishPath: ./appclient/build
    plan: free
    envVars:
      - key: REACT_APP_API_URL
        value: mock