version: "3.9"
services:
  db:
    image: postgres:15
    container_name: db-handyman-postgress
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: handyman-api
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data


